---
title: "Invesment Viz"
format: dashboard
theme: 
  - darkly
execute: 
  echo: false
editor: visual
---

```{r}
pacman::p_load(tidyverse, tidyquant,
               timetk, plotly,glue)
```


```{r}
SGStock <- read.csv("data/SGStock.csv")
```


```{r}
daily_prices <- SGStock %>%
  select(Symbol) %>%
  tq_get(get  = "stock.prices",
         from = "2025-01-01",
         to   = Sys.Date())

daily_prices <- daily_prices %>%
  left_join(SGStock, by = "Symbol")
```

# DBS 

```{r}
start_date <- min(daily_prices$date)
end_date <- max(daily_prices$date)
```

## Row {height=20%}

```{r}
daily_summary <- daily_prices%>%
  filter(Symbol == "D05.SI" & date == end_date)
```

```{r}
#| content: valuebox
#| title: "Opening Price"
list(color = "primary",
     value = daily_summary$open)
```

```{r}
#| content: valuebox
#| title: "Closing Price"
list(color = "primary",
     value = daily_summary$close)
```

```{r}
#| content: valuebox
#| title: "Daily High"
list(color = "primary",
     value = daily_summary$high)
```

```{r}
#| content: valuebox
#| title: "Daily Low"
list(color = "primary",
     value = daily_summary$low)
```

## Row

```{r}
# preparing the data
df <- daily_prices %>%
  filter(Name == "DBS Group")

mean_close <- mean(df$close, na.rm = TRUE)
sd_close <- sd(df$close, na.rm = TRUE)
ucl <- mean_close + 1 * sd_close
lcl <- mean_close - 1 * sd_close

df <- df %>%
  mutate(flag = case_when(
    close > ucl  ~ "Above UCL",
    close < lcl  ~ "Below LCL",
    TRUE ~ "Within Limits"))

mean_lbl <- paste0("Mean: ", round(mean_close, 2))
ucl_lbl  <- paste0("UCL: ", round(ucl,2))
lcl_lbl  <- paste0("LCL: ", round(lcl,2))

start_lbl <- format(start_date, "%d %B %Y")
end_lbl <- format(end_date, "%d %B %Y")
start_lbl <- sub("^0", "", start_lbl)
end_lbl <- sub("^0", "", end_lbl)

dynamic_title <- glue("DBS stock Prices from {start_lbl} to {end_lbl}")
```

```{r}
p <- ggplot(df, aes(x = date, y = close)) +
  geom_line(color = "steelblue") +
  geom_hline(
    yintercept = mean_close,
    color      = "grey0",
    linetype   = "dashed",
    size       = 0.5,
    alpha      = 0.8
  ) +
  geom_hline(
    yintercept = ucl,
    color      = "red",
    linetype   = "dotted",
    size       = 0.5,
    alpha      = 0.8
  ) +
  geom_hline(
    yintercept = lcl,
    color      = "red",
    linetype   = "dotted",
    size       = 0.5,
    alpha      = 0.8
  ) +
  geom_point(
    aes(color = flag),
    size = 1
  ) +
  annotate(
    "text",
    x     = min(df$date),
    y     = ucl + 0.3,
    label = ucl_lbl,
    hjust = 0,
    color = "red",
    size  = 3.5
  ) +
  annotate(
    "text",
    x     = min(df$date),
    y     = lcl + 0.3,
    label = lcl_lbl,
    hjust = 0,
    color = "red",
    size  = 3.5
  ) +
  annotate(
    "text",
    x     = min(df$date),
    y     = mean_close + 0.3,
    label = mean_lbl,
    hjust = 0,
    color = "darkgreen",
    size  = 3.5
  ) +
  scale_color_manual(
    values = c(
      "Above UCL"     = "red",
      "Below LCL"     = "red",
      "Within Limits" = "steelblue"
    )
  ) +
  scale_x_date(
    date_breaks = "1 month",
    date_labels = "%b %Y"
  ) +
  labs(
    title = dynamic_title,
    y     = "Closing Price",
    x     = ""
  ) +
  theme_classic()

ggplotly(p)
```

```{r}
plot_ly(
  df,
  x     = ~date,
  type  = "candlestick",
  open  = ~open,
  high  = ~high,
  low   = ~low,
  close = ~close,
  name  = "Price"
) %>%
  add_lines(
    x    = ~date,
    y    = ~TTR::SMA(close, n = 5),
    name = "SMA 5",
    line = list(
      dash  = "dot",
      width = 1.5
    )
  ) %>%
  add_lines(
    x    = ~date,
    y    = ~TTR::SMA(close, n = 15),
    name = "SMA 15",
    line = list(
      color = "red",
      width = 1.5
    )
  ) %>%
  layout(
    title = "Technical Analysis of DBS Stock Prices",
    yaxis = list(title = "Closing Price"),
    xaxis = list(title = "Date")
  )
```

# OCBC
```{r}
ocbc_summary <- daily_prices %>%
  filter(Symbol == "O39.SI", date == end_date)
```
## Row {height=20%}
```{r}
#| content: valuebox
#| title: "OCBC Opening Price"
list(color = "primary", value = ocbc_summary$open)
```

```{r}
#| content: valuebox
#| title: "OCBC Closing Price"
list(color = "primary", value = ocbc_summary$close)
```

```{r}
#| content: valuebox
#| title: "OCBC Daily High"
list(color = "primary", value = ocbc_summary$high)
```

```{r}
#| content: valuebox
#| title: "OCBC Daily Low"
list(color = "primary", value = ocbc_summary$low)
```
## Row 

```{r}
df_ocbc <- daily_prices %>%
  filter(Name == "OCBC Bank")
```

```{r}
mean_ocbc <- mean(df_ocbc$close, na.rm = TRUE)
sd_ocbc   <- sd(df_ocbc$close, na.rm = TRUE)
ucl_ocbc  <- mean_ocbc + sd_ocbc
lcl_ocbc  <- mean_ocbc - sd_ocbc

df_ocbc <- df_ocbc %>%
  mutate(flag = case_when(
    close > ucl_ocbc  ~ "Above UCL",
    close < lcl_ocbc  ~ "Below LCL",
    TRUE              ~ "Within Limits"
  ))

title_ocbc <- glue("OCBC stock Prices from {start_lbl} to {end_lbl}")

p_ocbc <- ggplot(df_ocbc, aes(date, close)) +
  geom_line(colour = "steelblue") +
  geom_hline(yintercept = mean_ocbc, linetype = "dashed", size = 0.5, alpha = 0.8) +
  geom_hline(yintercept = ucl_ocbc,     linetype = "dotted", size = 0.5, alpha = 0.8) +
  geom_hline(yintercept = lcl_ocbc,     linetype = "dotted", size = 0.5, alpha = 0.8) +
  geom_point(aes(colour = flag), size = 1) +
  annotate("text", x = min(df_ocbc$date), y = ucl_ocbc + 0.3, label = paste0("UCL: ", round(ucl_ocbc, 2)), hjust = 0) +
  annotate("text", x = min(df_ocbc$date), y = lcl_ocbc + 0.3, label = paste0("LCL: ", round(lcl_ocbc, 2)), hjust = 0) +
  annotate("text", x = min(df_ocbc$date), y = mean_ocbc + 0.3, label = paste0("Mean: ", round(mean_ocbc, 2)), hjust = 0, colour = "darkgreen") +
  scale_colour_manual(values = c("Above UCL" = "red", "Below LCL" = "red", "Within Limits" = "steelblue")) +
  scale_x_date(date_breaks = "1 month", date_labels = "%b %Y") +
  labs(title = title_ocbc, y = "Closing Price", x = NULL) +
  theme_classic()

ggplotly(p_ocbc)
```

```{r}
plot_ly(
  df_ocbc,
  x     = ~date,
  type  = "candlestick",
  open  = ~open,
  high  = ~high,
  low   = ~low,
  close = ~close,
  name  = "Price"
) %>%
  add_lines(x = ~date, y = ~TTR::SMA(close, 5), name = "SMA 5", line = list(dash = "dot", width = 1.5)) %>%
  add_lines(x = ~date, y = ~TTR::SMA(close, 15), name = "SMA 15", line = list(color = "red", width = 1.5)) %>%
  layout(title = "Technical Analysis of OCBC Stock Prices", yaxis = list(title = "Closing Price"), xaxis = list(title = "Date"))
```

# UOB

```{r}
uob_summary <- daily_prices %>%
  filter(Symbol == "U11.SI", date == end_date)
```
## Row {height=20%}
```{r}
#| content: valuebox
#| title: "UOB Opening Price"
list(color = "primary", value = uob_summary$open)
```

```{r}
#| content: valuebox
#| title: "UOB Closing Price"
list(color = "primary", value = uob_summary$close)
```

```{r}
#| content: valuebox
#| title: "UOB Daily High"
list(color = "primary", value = uob_summary$high)
```

```{r}
#| content: valuebox
#| title: "UOB Daily Low"
list(color = "primary", value = uob_summary$low)
```
## Row

```{r}
df_uob   <- daily_prices %>% filter(Name == "UOB")
mean_uob <- mean(df_uob$close, na.rm = TRUE)
sd_uob   <- sd(df_uob$close, na.rm = TRUE)
ucl_uob  <- mean_uob + sd_uob
lcl_uob  <- mean_uob - sd_uob

df_uob <- df_uob %>%
  mutate(flag = case_when(
    close > ucl_uob ~ "Above UCL",
    close < lcl_uob ~ "Below LCL",
    TRUE            ~ "Within Limits"
  ))

title_uob <- glue("UOB stock Prices from {start_lbl} to {end_lbl}")

p_uob <- ggplot(df_uob, aes(date, close)) +
  geom_line(colour = "steelblue") +
  geom_hline(yintercept = mean_uob,   linetype = "dashed", size = 0.5) +
  geom_hline(yintercept = ucl_uob,    linetype = "dotted", size = 0.5) +
  geom_hline(yintercept = lcl_uob,    linetype = "dotted", size = 0.5) +
  geom_point(aes(colour = flag), size = 1) +
  scale_colour_manual(values = c("Above UCL" = "red", "Below LCL" = "red", "Within Limits" = "steelblue")) +
  scale_x_date(date_breaks = "1 month", date_labels = "%b %Y") +
  labs(title = title_uob, y = "Closing Price", x = NULL) +
  theme_classic()

ggplotly(p_uob)
```

```{r}
plot_ly(
  df_uob,
  x     = ~date,
  type  = "candlestick",
  open  = ~open,
  high  = ~high,
  low   = ~low,
  close = ~close
) %>%
  add_lines(x = ~date, y = ~TTR::SMA(close, 5), name = "SMA 5", line = list(dash = "dot", width = 1.5)) %>%
  add_lines(x = ~date, y = ~TTR::SMA(close, 15), name = "SMA 15", line = list(color = "red", width = 1.5)) %>%
  layout(title = "Technical Analysis of UOB Stock Prices", yaxis = list(title = "Closing Price"), xaxis = list(title = "Date"))
```

# Singtel
```{r}
st_summary <- daily_prices %>%
  filter(Symbol == "Z74.SI", date == end_date)
```
## Row {height=20%}
```{r}
#| content: valuebox
#| title: "Singtel Opening Price"
list(color = "primary", value = st_summary$open)
```

```{r}
#| content: valuebox
#| title: "Singtel Closing Price"
list(color = "primary", value = st_summary$close)
```

```{r}
#| content: valuebox
#| title: "Singtel Daily High"
list(color = "primary", value = st_summary$high)
```

```{r}
#| content: valuebox
#| title: "Singtel Daily Low"
list(color = "primary", value = st_summary$low)
```

## Row

```{r}
df_st   <- daily_prices %>% filter(Name == "Singtel")
mean_st <- mean(df_st$close, na.rm = TRUE)
sd_st   <- sd(df_st$close, na.rm = TRUE)
ucl_st  <- mean_st + sd_st
lcl_st  <- mean_st - sd_st

df_st <- df_st %>%
  mutate(flag = case_when(
    close > ucl_st ~ "Above UCL",
    close < lcl_st ~ "Below LCL",
    TRUE           ~ "Within Limits"
  ))

title_st <- glue("Singtel stock Prices from {start_lbl} to {end_lbl}")

p_st <- ggplot(df_st, aes(date, close)) +
  geom_line() +
  geom_hline(yintercept = c(mean_st, ucl_st, lcl_st), linetype = c("dashed", "dotted", "dotted")) +
  geom_point(aes(colour = flag), size = 1) +
  scale_colour_manual(values = c("Above UCL" = "red", "Below LCL" = "red", "Within Limits" = "steelblue")) +
  scale_x_date(date_breaks = "1 month", date_labels = "%b %Y") +
  labs(title = title_st, y = "Closing Price", x = NULL) +
  theme_classic()

ggplotly(p_st)
```

```{r}
plot_ly(
  df_st,
  x     = ~date,
  type  = "candlestick",
  open  = ~open,
  high  = ~high,
  low   = ~low,
  close = ~close
) %>%
  add_lines(x = ~date, y = ~TTR::SMA(close, 5), name = "SMA 5", line = list(dash = "dot", width = 1.5)) %>%
  add_lines(x = ~date, y = ~TTR::SMA(close, 15), name = "SMA 15", line = list(color = "red", width = 1.5)) %>%
  layout(title = "Technical Analysis of Singtel Stock Prices", yaxis = list(title = "Closing Price"), xaxis = list(title = "Date"))
```

# SIA
```{r}
sia_summary <- daily_prices %>%
  filter(Symbol == "C6L.SI", date == end_date)
```
## Row {height=20%}

```{r}
#| content: valuebox
#| title: "SIA Opening Price"
list(color = "primary", value = sia_summary$open)
```

```{r}
#| content: valuebox
#| title: "SIA Closing Price"
list(color = "primary", value = sia_summary$close)
```

```{r}
#| content: valuebox
#| title: "SIA Daily High"
list(color = "primary", value = sia_summary$high)
```

```{r}
#| content: valuebox
#| title: "SIA Daily Low"
list(color = "primary", value = sia_summary$low)
```

## Row 

```{r}
df_sia   <- daily_prices %>% filter(Name == "Singapore Airlines")
mean_sia <- mean(df_sia$close, na.rm = TRUE)
sd_sia   <- sd(df_sia$close, na.rm = TRUE)
ucl_sia  <- mean_sia + sd_sia
lcl_sia  <- mean_sia - sd_sia

df_sia <- df_sia %>%
  mutate(flag = case_when(
    close > ucl_sia ~ "Above UCL",
    close < lcl_sia ~ "Below LCL",
    TRUE            ~ "Within Limits"
  ))

title_sia <- glue("SIA stock Prices from {start_lbl} to {end_lbl}")

p_sia <- ggplot(df_sia, aes(date, close)) +
  geom_line(colour = "steelblue") +
  geom_hline(yintercept = mean_sia,   linetype = "dashed") +
  geom_hline(yintercept = c(ucl_sia, lcl_sia), linetype = "dotted") +
  geom_point(aes(colour = flag), size = 1) +
  scale_colour_manual(values = c("Above UCL" = "red", "Below LCL" = "red", "Within Limits" = "steelblue")) +
  scale_x_date(date_breaks = "1 month", date_labels = "%b %Y") +
  labs(title = title_sia, y = "Closing Price", x = NULL) +
  theme_classic()

ggplotly(p_sia)
```

```{r}
plot_ly(
  df_sia,
  x     = ~date,
  type  = "candlestick",
  open  = ~open,
  high  = ~high,
  low   = ~low,
  close = ~close
) %>%
  add_lines(x = ~date, y = ~TTR::SMA(close, 5), name = "SMA 5", line = list(dash = "dot", width = 1.5)) %>%
  add_lines(x = ~date, y = ~TTR::SMA(close, 15), name = "SMA 15", line = list(color = "red", width = 1.5)) %>%
  layout(title = "Technical Analysis of SIA Stock Prices", yaxis = list(title = "Closing Price"), xaxis = list(title = "Date"))
```

# CapitaLand Mall Trust 
```{r}
cmt_summary <- daily_prices %>%
  filter(Symbol == "C38U.SI", date == end_date)
```
## Row {height=20%}
```{r}
#| content: valuebox
#| title: "CMT Opening Price"
list(color = "primary", value = cmt_summary$open)
```

```{r}
#| content: valuebox
#| title: "CMT Closing Price"
list(color = "primary", value = cmt_summary$close)
```

```{r}
#| content: valuebox
#| title: "CMT Daily High"
list(color = "primary", value = cmt_summary$high)
```

```{r}
#| content: valuebox
#| title: "CMT Daily Low"
list(color = "primary", value = cmt_summary$low)
```

## Row

```{r}
df_cmt   <- daily_prices %>% filter(Name == "CapitaLand Mall Trust")
mean_cmt <- mean(df_cmt$close, na.rm = TRUE)
sd_cmt   <- sd(df_cmt$close, na.rm = TRUE)
ucl_cmt  <- mean_cmt + sd_cmt
lcl_cmt  <- mean_cmt - sd_cmt

df_cmt <- df_cmt %>%
  mutate(flag = case_when(
    close > ucl_cmt ~ "Above UCL",
    close < lcl_cmt ~ "Below LCL",
    TRUE            ~ "Within Limits"
  ))

title_cmt <- glue("CMT stock Prices from {start_lbl} to {end_lbl}")

p_cmt <- ggplot(df_cmt, aes(date, close)) +
  geom_line(colour = "steelblue") +
  geom_hline(yintercept = mean_cmt,   linetype = "dashed") +
  geom_hline(yintercept = c(ucl_cmt, lcl_cmt), linetype = "dotted") +
  geom_point(aes(colour = flag), size = 1) +
  scale_colour_manual(values = c("Above UCL" = "red", "Below LCL" = "red", "Within Limits" = "steelblue")) +
  scale_x_date(date_breaks = "1 month", date_labels = "%b %Y") +
  labs(title = title_cmt, y = "Closing Price", x = NULL) +
  theme_classic()

ggplotly(p_cmt)
```

```{r}
plot_ly(
  df_cmt,
  x     = ~date,
  type  = "candlestick",
  open  = ~open,
  high  = ~high,
  low   = ~low,
  close = ~close
) %>%
  add_lines(x = ~date, y = ~TTR::SMA(close, 5), name = "SMA 5", line = list(dash = "dot", width = 1.5)) %>%
  add_lines(x = ~date, y = ~TTR::SMA(close, 15), name = "SMA 15", line = list(color = "red", width = 1.5)) %>%
  layout(title = "Technical Analysis of CMT Stock Prices", yaxis = list(title = "Closing Price"), xaxis = list(title = "Date"))
```
